### ISSUE TITLE
Don't work whith gulp 4

### ISSUE THREAD

**Issue by pvlv** [cmtt/gulp-di#9]
node -v 
`v6.5.0`

``` json
{
  "name": "gulpdi-test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "gulp": "gulp"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.18.0",
    "babel-register": "^6.18.0",
    "del": "^2.2.2",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-debug": "^2.1.2",
    "gulp-di": "0.0.33",
    "gulp-sass": "^2.3.2",
    "make-targs": "github:pvlv/make-targs#v1.0.0",
    "run-sequence": "^1.2.2"
  }
}
```

``` js
// /tasks/styles.js

'use strict';

module.exports = (gulp, sass) => {
  gulp.task('styles', () => {
    return gulp.src('./fixtures/styles/*.scss')
      .pipe(sass())
      .pipe(gulp.dest('./results/css/'));
  })
}
```

``` js
// /tasks/default.js

'use strict';

module.exports = function (gulp) {
  gulp.task('default', gulp.parallel(
      'styles'
  ));
}

```

``` js
// /gulpfile.js

const gulp = require('gulp');

const di = require('gulp-di')(gulp, {
  pattern: ['gulp-*', 'gulp.*']
});

di
  .tasks('./tasks')
  .resolve();

module.exports = gulp;
```

Stack trace

``` bash
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: styles
    at getFunction (/data/node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at arrayMap (/data/node_modules/lodash.map/index.js:140:21)
    at map (/data/node_modules/lodash.map/index.js:1836:10)
    at normalizeArgs (/data/node_modules/undertaker/lib/helpers/normalizeArgs.js:19:10)
    at Gulp.parallel (/data/node_modules/undertaker/lib/parallel.js:13:14)
    at GulpDI.module.exports (/data/tasks/default.js:4:29)
    at GulpDI.resolve (/data/node_modules/gulp-di/lib/di.js:261:34)
    at Object.<anonymous> (/data/gulpfile.js:10:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

If install gulp `3.8.1` - gulp-di work correctly

**Comment by cmtt** [comment]
Hello pvlv,

thanks a lot for reporting this issue. I can confirm the issue and will check whether compatibility with gulp 4.x can be achieved.

**Comment by cmtt** [comment]
@pvlv. initial support for Gulp 4.0 has been added in branch "4.0" (``github:cmtt/gulp-di#4.0``) 
This is a work-in-progress effort, so this branch might be unstable.

**Comment by cmtt** [comment]
Closing this issue, as there is now basic Gulp 4 support in the aforementioned branch. 
When Gulp 4 will be released, this project will follow.
